### ISSUE TITLE
embeds, _, attention_mask = clip.cond_stage_model.t5xxl.encode_token_weights(tokens)

### ISSUE THREAD

**Issue by weisihao** [kijai/ComfyUI-MochiWrapper#14]
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by zishen-ucap** [comment]
+1

**Comment by kijai** [comment]
Is your ComfyUI up to date? the ability to get attention mask from T5 was added recently, which is what I'm using, so it will fail with older Comfy versions.

**Comment by zishen-ucap** [comment]
> Is your ComfyUI up to date? the ability to get attention mask from T5 was added recently, which is what I'm using, so it will fail with older Comfy versions.

The ComfyUI update did indeed solve this issue.
