### ISSUE TITLE
MochiModelLoader ： 'pos_frequencies'

### ISSUE THREAD

**Issue by kaixinmalo** [kijai/ComfyUI-MochiWrapper#23]
![image](https://github.com/user-attachments/assets/7bd2dd6f-f1b7-4b8f-8147-1837606d485e)

**Comment by kijai** [comment]
You have the models swapped there.

**Comment by kaixinmalo** [comment]
> You have the models swapped there.你在那里交换了模型。

Sorry, I was a bit careless, I'll try again now

**Comment by kaixinmalo** [comment]
> You have the models swapped there.

New error：name 'sageattn' is not defined.Is that how it's installed?

![image](https://github.com/user-attachments/assets/107c41fc-4026-4398-a5b8-ec50b8d53ae5)
