### ISSUE TITLE
Default CFG

### ISSUE THREAD

**Issue by jpgallegoar** [kijai/ComfyUI-MochiWrapper#24]
Why was 4.5 selected as the default CFG? I tested 7.5 and it's much better quality. Probably there's a better value but haven't had time to test yet.

**Comment by kijai** [comment]
I don't know, that's what they had as default so I didn't change that. You're right that higher values seem to work well too, no idea what's the optimal choice.

**Comment by MushroomFleet** [comment]
> > I don't know, that's what they had as default so I didn't change that. You're right that higher values seem to work well too, no idea what's the optimal choice.
> 
> I will try to test as many as I can in 0.5 increments, and let you know. 3 of each to average out. It will take a while.

am also eager to see your results ! great recommendation for trying 7 CFG. Big Thanks

**Comment by festivus37** [comment]
https://github.com/user-attachments/assets/0fc

https://github.com/user-attachments/assets/60de1446-a08e-4770-a4d4-c1c7fe546102

27f54-33d3-4d14-acd4-0ca4bab40c8d

I don't know if these videos will upload, but the lower quality one is 4.5, the higher quality one is 7.  same seed and step count. the difference is huge.

**Comment by festivus37** [comment]
https://github.com/user-attachments/assets/c2f1daab-09de-4ad0-a9bf-c2c988cdcf10

this one is cfg 7

**Comment by kijai** [comment]
If you want to really get into it, I added option to use custom sigma schedules, by default it's same cfg for each step, but you can give it a list of cfg values as well, for example with my SplineEditor:

![image](https://github.com/user-attachments/assets/eddb574b-4003-41a2-96f5-5129ab3b54cb)
