### ISSUE TITLE
2 GPU Optimisations

### ISSUE THREAD

**Issue by Manimap** [kijai/ComfyUI-MochiWrapper#27]
Hi, 

I tried it and it works perfectly well with a 3090 with the example workflow you provided (on ubuntu), but I was wondering if there was anything I could to to also use the second 3090 I have in the system, or in fact it was completely limited to 1 GPU only?

**Comment by kijai** [comment]
It's limited to on GPU, the underlaying code can support multiple ones, but it's somewhat more complicated to do in Comfy, and I don't have multiple GPUs to work on that.
