### ISSUE TITLE
360p

### ISSUE THREAD

**Issue by jikkuatwork** [kijai/ComfyUI-MochiWrapper#29]
I think if this can be targeted to generated super tiny videos like 360p, it may work on a large number of devices and then it can be adapted work with larger resolutions.

This gets more people to be involved accelerating the improvement. 

Context: The CSGO world generation demo was targeting an even tiny resolution; not great but it worked with a single command in a relatively weak GPU like RTX3060! I think thats a great direction to take

**Comment by kijai** [comment]
Sure, but I don't have anything to do with how the model was trained, the optimal resolution for this specific model currently is the 848x480 and everything else tends to be worse in quality, though many other resolutions do already work to an extend.

**Comment by jikkuatwork** [comment]
Wouldn't reducing the resolution mean reduction in VRAM utilisation even though their resolution was different?

**Comment by kijai** [comment]
> Wouldn't reducing the resolution mean reduction in VRAM utilisation even though their resolution was different?

Yes, and you can do that, but it also reduces quality of the motion in most cases.

**Comment by jikkuatwork** [comment]
Yes, that happened! I was wondering why. Probably the frames's composition gets messed up at arbitrary resolutions because the model may be assuming all videos are of that size and  hard-coded that information and assumes it while generating.
