### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by T8mars** [kijai/ComfyUI-MochiWrapper#3]
![image](https://github.com/user-attachments/assets/046a0355-0fa9-47c3-9842-20282e68f6e2)
hi,is the whl don't support windows?

**Comment by T8mars** [comment]
I download it from your HF
![image](https://github.com/user-attachments/assets/12832697-2b2c-437b-8b9a-30deb608bd31)

**Comment by kijai** [comment]
The platform also means python version, this is for 3.12.

**Comment by TheRohitSharma** [comment]
I get this as well, even with python 3.12. I have CUDA 12.4. @kijai Is CUDA 12.5 required here or is 12.4 okay? I see the README mention 12.4, but the flash_attn filename includes cu125.

**Comment by T8mars** [comment]
I'm sorry,can the node support py3.10 torch 2.3 cuda124 with flash attn?

**Comment by kijai** [comment]
> I'm sorry,can the node support py3.10 torch 2.3 cuda124 with flash attn?

That's pretty old torch by now and not recommended to use anyway. Flash attention is needed by mochi itself, so I don't know if it can be done without it.

**Comment by kijai** [comment]
> I get this as well, even with python 3.12. I have CUDA 12.4. @kijai Is CUDA 12.5 required here or is 12.4 okay? Or would that not cause this error? I see the README mention 12.4, but the flash_attn filename includes cu125.

Should be okay, minor version mismatches don't really matter, I'm using 12.4 torch too even if I compiled with cuda-toolkit 125.

**Comment by ThatDocBoi** [comment]
> > I get this as well, even with python 3.12. I have CUDA 12.4. @kijai Is CUDA 12.5 required here or is 12.4 okay? Or would that not cause this error? I see the README mention 12.4, but the flash_attn filename includes cu125.
> 
> Should be okay, minor version mismatches don't really matter, I'm using 12.4 torch too even if I compiled with cuda-toolkit 125.

I'm getting the not wheel supported error with a brand new comfy portable with python 3.12 and pytorch 2.5 install (v0.2.4 portable release from yesterday) with the -m pip install option. Not sure if I'm I doing something wrong.

**Comment by kijai** [comment]
> > > I get this as well, even with python 3.12. I have CUDA 12.4. @kijai Is CUDA 12.5 required here or is 12.4 okay? Or would that not cause this error? I see the README mention 12.4, but the flash_attn filename includes cu125.
> > 
> > 
> > Should be okay, minor version mismatches don't really matter, I'm using 12.4 torch too even if I compiled with cuda-toolkit 125.
> 
> I'm getting the not wheel supported error with a brand new comfy portable with python 3.12 and pytorch 2.5 install (v0.2.4 portable release from yesterday) with the -m pip install option. The only mismatch is cuda from what I can see, mine is 12.4. Not sure if I'm I doing something wrong.

Hmm I thought it'd work, I don't have much experience with building and sharing wheels so it's possible I did something wrong. Is it Windows 11?

**Comment by ThatDocBoi** [comment]
> > > > I get this as well, even with python 3.12. I have CUDA 12.4. @kijai Is CUDA 12.5 required here or is 12.4 okay? Or would that not cause this error? I see the README mention 12.4, but the flash_attn filename includes cu125.
> > > 
> > > 
> > > Should be okay, minor version mismatches don't really matter, I'm using 12.4 torch too even if I compiled with cuda-toolkit 125.
> > 
> > 
> > I'm getting the not wheel supported error with a brand new comfy portable with python 3.12 and pytorch 2.5 install (v0.2.4 portable release from yesterday) with the -m pip install option. The only mismatch is cuda from what I can see, mine is 12.4. Not sure if I'm I doing something wrong.
> 
> Hmm I thought it'd work, I don't have much experience with building and sharing wheels so it's possible I did something wrong. Is it Windows 11?

Windows 10

**Comment by TheRohitSharma** [comment]
![Capture](https://github.com/user-attachments/assets/9d005ba2-25c9-4dca-ac27-2f242de7fdcc)

This is what happens in my case. If I try to use the model, it gives me an out-of-memory error at model loading time. RTX 4090 here.

**Comment by kijai** [comment]
> > > > > I get this as well, even with python 3.12. I have CUDA 12.4. @kijai Is CUDA 12.5 required here or is 12.4 okay? Or would that not cause this error? I see the README mention 12.4, but the flash_attn filename includes cu125.
> > > > 
> > > > 
> > > > Should be okay, minor version mismatches don't really matter, I'm using 12.4 torch too even if I compiled with cuda-toolkit 125.
> > > 
> > > 
> > > I'm getting the not wheel supported error with a brand new comfy portable with python 3.12 and pytorch 2.5 install (v0.2.4 portable release from yesterday) with the -m pip install option. The only mismatch is cuda from what I can see, mine is 12.4. Not sure if I'm I doing something wrong.
> > 
> > 
> > Hmm I thought it'd work, I don't have much experience with building and sharing wheels so it's possible I did something wrong. Is it Windows 11?
> 
> Windows 10

That could be it, as I compiled on Win11.

**Comment by kijai** [comment]
Actually looks like I can't change the wheel name, it wouldn't install for me again until I renamed it back to what it was:
`flash_attn-2.6.3-cp312-cp312-win_amd64.whl`

**Comment by TheRohitSharma** [comment]
Ah, thanks! I was able to install it that way. I still get:

`Requested to load SD3ClipModel_
Loading 1 new model
loaded completely 0.0 4541.693359375 True
Timing construct_dit
Timing dit_load_checkpoint
Loading model state_dict from D:\comfyui\comfyui\models\diffusion_models\mochi\mochi_preview_dit_fp8_e4m3fn.safetensors...
Press any key to continue . . .`

Hopefully I'll be able to figure it out.

**Comment by kijai** [comment]
> Ah, thanks! I was able to install it that way by renaming the .whl. I still get:
> 
> ```
> Loading 1 new model
> loaded completely 0.0 4541.693359375 True
> Timing construct_dit
> Timing dit_load_checkpoint
> Loading model state_dict from D:\comfyui\comfyui\models\diffusion_models\mochi\mochi_preview_dit_fp8_e4m3fn.safetensors...
> Press any key to continue . . .
> ```
> 
> Hopefully I'll be able to figure it out.

It does use quite a bit of RAM, are you checking you aren't running out of it?

**Comment by D3voz** [comment]
Hi, shall i use the t5xxl text encoder clip or need to download something else?

**Comment by TheRohitSharma** [comment]
> > Ah, thanks! I was able to install it that way by renaming the .whl. I still get:
> > ```
> > Loading 1 new model
> > loaded completely 0.0 4541.693359375 True
> > Timing construct_dit
> > Timing dit_load_checkpoint
> > Loading model state_dict from D:\comfyui\comfyui\models\diffusion_models\mochi\mochi_preview_dit_fp8_e4m3fn.safetensors...
> > Press any key to continue . . .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hopefully I'll be able to figure it out.
> 
> It does use quite a bit of RAM, are you checking you aren't running out of it?

Doesn't look like I'm running out of RAM. Maybe I'll redo comfyui without the portable version and try again. Likely not related to flash-attention at the model-loading stage, you think?

**Comment by kijai** [comment]
> > > Ah, thanks! I was able to install it that way by renaming the .whl. I still get:
> > > ```
> > > Loading 1 new model
> > > loaded completely 0.0 4541.693359375 True
> > > Timing construct_dit
> > > Timing dit_load_checkpoint
> > > Loading model state_dict from D:\comfyui\comfyui\models\diffusion_models\mochi\mochi_preview_dit_fp8_e4m3fn.safetensors...
> > > Press any key to continue . . .
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Hopefully I'll be able to figure it out.
> > 
> > 
> > It does use quite a bit of RAM, are you checking you aren't running out of it?
> 
> Doesn't look like I'm running out of RAM. Maybe I'll redo comfyui without the portable version and try again. Likely not related to flash-attention at the model-loading stage, you think?

Can you try installing `accelerate`?

**Comment by D3voz** [comment]
![c201134](https://github.com/user-attachments/assets/097e3287-a081-4515-b282-0dc99ee37b48)
I got it running but it is not using the bf16 model. When i put the bf16 model and start it, it just downloads the fp8 model and uses that.

**Comment by kijai** [comment]
> ![c201134](https://private-user-images.githubusercontent.com/139697969/379448819-097e3287-a081-4515-b282-0dc99ee37b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MTc1NTksIm5iZiI6MTcyOTcxNzI1OSwicGF0aCI6Ii8xMzk2OTc5NjkvMzc5NDQ4ODE5LTA5N2UzMjg3LWEwODEtNDUxNS1iMjgyLTBkYzk5ZWUzN2I0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QyMTAwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjg0Zjk0NzMzZGU3OWFmMTU2OTRlZWUwZTNhYjk5OTIwYzQ1OGNhODNhYzVlZTQyYzk1OWNkODVhMGM3MDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FChQgsXG5NUvghPac39TxuiW92--myMx6X6vWi3HGw8) I got it running but it is not using the bf16 model. When i put the bf16 model and start it, it just downloads the fp8 model and uses that.

Right, yeah I forgot to add it to the selection, it's selectable now as a model.

**Comment by TheRohitSharma** [comment]
> Can you try installing `accelerate`?

Your latest commits (not sure which ones) solved it. Thanks!

**Comment by kijai** [comment]
Flash attention should no longer be required.
