### ISSUE TITLE
"MochiSampler No available kernel. Aborting execution." had gone after last git pull

### ISSUE THREAD

**Issue by ptits** [kijai/ComfyUI-MochiWrapper#35]
I can confirm that after last update kernels error has gone.
H100 80GB VRAM
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:10:22_PDT_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0

**Comment by kijai** [comment]
Alright thanks, what I learned was that when given list of backends, torch tries to use them in the order they are in the list.
