### ISSUE TITLE
BF16 model

### ISSUE THREAD

**Issue by mikeyimer** [kijai/ComfyUI-MochiWrapper#4]
Are there any plans to produce a bf16 quantization model?  whether they can run on a 32GB VRAM

**Comment by kijai** [comment]
Yeah I have just haven't uploaded it yet.

**Comment by kijai** [comment]
Uploaded but untested:

https://huggingface.co/Kijai/Mochi_preview_comfy/blob/main/mochi_preview_dit_bf16.safetensors

**Comment by gtbloody** [comment]
> Uploaded but untested:
> 
> https://huggingface.co/Kijai/Mochi_preview_comfy/blob/main/mochi_preview_dit_bf16.safetensors

FP4 plz!
