### ISSUE TITLE
cfg_schedule  > 0 causes error

### ISSUE THREAD

**Issue by ptits** [kijai/ComfyUI-MochiWrapper#41]
Using cfg schedule: 0.1
!!! Exception during processing !!! object of type 'float' has no len()
Traceback (most recent call last):
  File "/home/jovyan/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jovyan/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 401, in process
    latents = model.run(args)
              ^^^^^^^^^^^^^^^
  File "/home/jovyan/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/mochi_preview/t2v_synth_mochi.py", line 241, in run
    len(cfg_schedule) == sample_steps
    ^^^^^^^^^^^^^^^^^
TypeError: object of type 'float' has no len()

**Comment by ptits** [comment]
what is cfg schedule for?

**Comment by kijai** [comment]
It takes in list of ints, as many as there are steps, not just one. It's to set cfg for each step separately.

**Comment by ptits** [comment]
![shot_241029_020825](https://github.com/user-attachments/assets/c29b7445-fcca-4870-a928-15b1f5483578)
it looks like it is not setable here

**Comment by kijai** [comment]
> ![shot_241029_020825](https://private-user-images.githubusercontent.com/13587736/380918100-c29b7445-fcca-4870-a928-15b1f5483578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjAzMzcsIm5iZiI6MTczMDE2MDAzNywicGF0aCI6Ii8xMzU4NzczNi8zODA5MTgxMDAtYzI5Yjc0NDUtZmNjYS00ODcwLWE5MjgtMTViMWY1NDgzNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAwMDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOGI3ZGY1Y2Q2YWMzOGYzZGE0ODdjOGVhOGFhMDI3NTZmMTdlZTlhZjE2MGNkODU3ZTlkZDRkYzBlYWQ3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kah1W8JHTdCzzNEqRgmB7WfavnlKQnHFujroOap1Htk) it looks like it is not setable here

It's not, that's a bug in comfy where inputs stay as widgets even if defined as forceinput, have to re-create the node to fix it (or right click and fix node).
