### ISSUE TITLE
Workflows are not loading in comfyui

### ISSUE THREAD

**Issue by fahdmirza** [kijai/ComfyUI-MochiWrapper#46]
Hi,
  On Ubuntu 22.04, where I have nvidia RTX A6000 and torch 2.4.1 and latest version of comfyui, I am loading the workflow json files in comfyui but they are not getting loaded and I get a blank screen. I have even done a fresh install of comfyui without any other custom nodes but still the same issue. I also have flash attention installed and it happens with and without it. I have also tried it in chrome, firefox , in-private window but same result as nothing appears in comfyui. please advise. Thanks.
regards,

**Comment by kshabanaa** [comment]
can you veiw a screenshot of what happened

**Comment by kshabanaa** [comment]
has you updated comfyui

**Comment by kshabanaa** [comment]
waiting for your video 😊😊😊

**Comment by kshabanaa** [comment]
cd to ComfyUI_windows_portable\ComfyUI\custom_nodes
then type "git clone https://github.com/kijai/ComfyUI-MochiWrapper.git"

**Comment by kshabanaa** [comment]
then refresh comfy ui

**Comment by fahdmirza** [comment]
Hi,
 As mentioned above, I have already done that and still the same error . I have even done fresh installation but still same issue.

**Comment by kijai** [comment]
What do you mean by "blank screen" ? There's no errors in the console or the browser console?

**Comment by fahdmirza** [comment]
yes there are no errors in console or browser console. Blank screen means that when I load the workflow in comfyUI , it doesn't show anything and comfyui screen remains blank. 

Thanks.

**Comment by kijai** [comment]
That's a Comfy issue then, I have no idea.

**Comment by fahdmirza** [comment]
No worries, I will do a fresh install on a new machine today and see how it goes. Could you please give me the link to clip model you used?

**Comment by kshabanaa** [comment]
i donot know try to install it again

**Comment by kijai** [comment]
> No worries, I will do a fresh install on a new machine today and see how it goes. Could you please give me the link to clip model you used?

It's same one as you use with Flux and SD3:

https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/t5xxl_fp8_e4m3fn.safetensors

**Comment by fahdmirza** [comment]
After fresh install on another machine, all works now. Here is the video I created for your awesome custom node, thanks

https://youtu.be/iSSKW5qLibU?si=53ue4rYkQq4T2TWr
