### ISSUE TITLE
Using tilted decode results in error on linux

### ISSUE THREAD

**Issue by CyberTimon** [kijai/ComfyUI-MochiWrapper#5]
Hi

Thank you for this wrapper. I'm trying to set it up myself but now I'm having the following problem:

- If tilted decoding is not used, it results in OOM (on a 3090)
- If tilted decoding is used, it results in the following error:

```
File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 325, in decode
row.append(torch.cat(time, dim=2))
^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: torch.cat(): expected a non-empty list of Tensors
^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

The workflow is exactly as shown in your video.
Do you know how I can fix this?

Kind regards,
Timon

**Comment by kijai** [comment]
Same frame count, or did you reduce the generated frames? The  `frame_batch_size` in the decoder can't be smaller than the generated latent count, which is approximately images divided by 6 (need to check the exact math on this).

**Comment by kijai** [comment]
Added better errors and handling for this, it won't try to tile decode if the frame_batch_size is larger than the actual sample count to decode.

**Comment by CyberTimon** [comment]
Thanks, I will test it again soon!
