### ISSUE TITLE
'T2VSynthMochiModel' object has no attribute 'dit'

### ISSUE THREAD

**Issue by janoschsimon** [kijai/ComfyUI-MochiWrapper#6]
Hey there  :) first of all thx for the great work  :)
i trid your preview and i get this error message:

```
FETCH DATA from: D:\AI-Stuff\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Downloading mochi VAE to: D:\AI-Stuff\ComfyUI\models\vae\mochi\mochi_preview_vae_bf16.safetensors
Fetching 1 files:   0%|                                                                          | 0/1 [00:00<?, ?it/s]C:\Users\janos\miniconda3\envs\comfyenv\Lib\site-packages\huggingface_hub\file_download.py:834: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
Fetching 1 files: 100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 499.74it/s]
Timing construct_dit
Timing dit_load_checkpoint
!!! Exception during processing !!! 'T2VSynthMochiModel' object has no attribute 'dit'
Traceback (most recent call last):
  File "D:\AI-Stuff\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Stuff\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Stuff\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI-Stuff\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Stuff\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 109, in loadmodel
    model = T2VSynthMochiModel(
            ^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Stuff\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\t2v_synth_mochi.py", line 163, in __init__
    for name, param in self.dit.named_parameters():
                       ^^^^^^^^
AttributeError: 'T2VSynthMochiModel' object has no attribute 'dit'
```

Prompt executed in 28.72 seconds

im on Windows 11 pro Python 3.12.7  4090 Cuda 12.4 
here is pip list
Package            Version
------------------ ------------
aiohappyeyeballs   2.4.3
aiohttp            3.10.10
aiosignal          1.3.1
attrs              24.2.0
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.4.0
click              8.1.7
color-matcher      0.5.0
colorama           0.4.6
contourpy          1.3.0
cryptography       43.0.3
cuda-python        12.6.0
cycler             0.12.1
ddt                1.7.2
Deprecated         1.2.14
docutils           0.21.2
einops             0.8.0
filelock           3.13.1
flash_attn         2.6.3
fonttools          4.54.1
frozenlist         1.5.0
fsspec             2024.2.0
gitdb              4.0.11
GitPython          3.1.43
huggingface-hub    0.26.1
idna               3.10
imageio            2.36.0
imageio-ffmpeg     0.5.1
Jinja2             3.1.3
kiwisolver         1.4.7
kornia             0.7.3
kornia_rs          0.1.5
markdown-it-py     3.0.0
MarkupSafe         2.1.5
matplotlib         3.9.2
matrix-client      0.4.0
mdurl              0.1.2
mpmath             1.3.0
mss                9.0.2
multidict          6.1.0
networkx           3.2.1
numpy              1.26.3
opencv-python      4.10.0.84
packaging          24.1
pillow             11.0.0
pip                24.2
propcache          0.2.0
psutil             6.1.0
pycparser          2.22
PyGithub           2.4.0
Pygments           2.18.0
PyJWT              2.9.0
PyNaCl             1.5.0
pyparsing          3.2.0
python-dateutil    2.9.0.post0
pywin32            307
PyYAML             6.0.2
regex              2024.9.11
requests           2.32.3
rich               13.9.3
safetensors        0.4.5
scipy              1.14.1
sentencepiece      0.2.0
setuptools         75.1.0
shellingham        1.5.4
six                1.16.0
smmap              5.0.1
soundfile          0.12.1
spandrel           0.4.0
sympy              1.13.1
tokenizers         0.20.1
torch              2.5.0+cu124
torchaudio         2.5.0+cu124
torchsde           0.2.6
torchvision        0.20.0+cu124
tqdm               4.66.5
trampoline         0.1.2
transformers       4.45.2
typer              0.12.5
typing_extensions  4.9.0
urllib3            1.26.20
wheel              0.44.0
wrapt              1.16.0
yarl               1.16.0

cheers and thx janosch

**Comment by kijai** [comment]
This was a bug I introduced by adding `accelerate` for model loading, for cases it's not installed. It's fixed now, but I'd still recommend installing `accelerate `as it speeds up the model loading some.

**Comment by janoschsimon** [comment]
worked mate thx a ton!  i installed accelerate  and updated the file now its running!
