### ISSUE TITLE
MochiSampler using Triton : ImportError: DLL load failed while importing __triton_launcher

### ISSUE THREAD

**Issue by Djanghost** [kijai/ComfyUI-MochiWrapper#62]
Having this error with the MochiSampler, can't use Triton in the latest version of ComfyUI (portable). _**It worked with the previous one (python 3.11)**_ 
The error occurs when trying to render with sage_attn mode, using the 'Mochi Torch Compile' node.
It seems to come directly from the node because my Triton installation is fine, with all the right prerequisite installed (cuda toolkit 12.5 in PATH etc...).

Current versions:

ComfyUI v0.2.6-9
Python Version : 3.12.7 (tags/v3.12.7:0b05ead, Oct 1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
Pytorch Version : 2.5.1+cu124

![Capture d'écran 2024-11-04 145931](https://github.com/user-attachments/assets/aed8bb89-f576-4468-b5cd-8841133f26ff)

**Comment by Ratinod** [comment]
Have you tried this?
https://forums.pokemmo.com/index.php?/topic/71562-moemon-star-emerald-and-mega-moemon-firered/page/69/
```
If you see `ImportError: DLL load failed`, and there are `vcruntime140.dll` and `vcruntime140_1.dll` in the folder containing `python.exe`, then you may try:

-   Install the latest version of vcredist from [https://aka.ms/vs/17/release/vc\_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)
-   Copy-paste `msvcp140.dll`, `vcruntime140.dll`, and `vcruntime140_1.dll` from `C:\Windows\System32\` to the folder containing `python.exe` (ComfyUI\python_embeded)
-   Delete the cache folder `C:\Users\<your username>\.triton\cache\`
```

**Comment by Ratinod** [comment]
Have you tried this?
https://github.com/woct0rdho/triton-windows?tab=readme-ov-file#test-if-it-works
```
If you see `ImportError: DLL load failed`, and there are `vcruntime140.dll` and `vcruntime140_1.dll` in the folder containing `python.exe`, then you may try:

-   Install the latest version of vcredist from [https://aka.ms/vs/17/release/vc\_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)
-   Copy-paste `msvcp140.dll`, `vcruntime140.dll`, and `vcruntime140_1.dll` from `C:\Windows\System32\` to the folder containing `python.exe` (comfy\python_embeded)
-   Delete the cache folder `C:\Users\<your username>\.triton\cache\`
```

**Comment by Djanghost** [comment]
Yes I've tried all the proposed solutions. I also opened a thread on the Triton repo just in case, even though it doesn't seem very active. 
I've even uninstalled Comfy, Cuda toolkit and everything else to reinstall everything but I still get the same error.

**Comment by Ratinod** [comment]
> Yes I've tried all the proposed solutions. I also opened a thread on the Triton repo just in case, even though it doesn't seem very active. I've even uninstalled Comfy, Cuda toolkit and everything else to reinstall everything but I still get the same error.

Try delete `msvcp140.dll`, `vcruntime140.dll`, and `vcruntime140_1.dll` from (comfy\python_embeded)
then copy from `C:\Windows\System32\` only `msvcp140.dll` and `vcruntime140.dll` to (comfy\python_embeded)

**Comment by Djanghost** [comment]
Same error! Thanks though

**Comment by Ratinod** [comment]
copy the error from the console

**Comment by Ratinod** [comment]
vcruntime140.dll - 119 888 bytes (117 kb) ? file version - 14.40.33816.0 ?
msvcp140.dll - 575 056 bytes (561kb) ? file version - 14.40.33816.0 ?

**Comment by Ratinod** [comment]
You can also try adding "FULL_PATH\comfy_folder\python_embeded" and  "FULL_PATH\comfy_folder\python_embeded\Scripts" to the Windows `PATH`
and don't forget to move it all up the list like this example:
```
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64
D:\ComfyUI_windows_portable_nvidia\python_embeded
D:\ComfyUI_windows_portable_nvidia\python_embeded\Scripts
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\lib\x64
everything else 1
everything else 2
...
```

**Comment by Djanghost** [comment]
> vcruntime140.dll - 119 888 bytes (117 kb) ? file version - 14.40.33816.0 ? msvcp140.dll - 575 056 bytes (561kb) ? file version - 14.40.33816.0 ?

Sorry but what does that mean ? That I have the wrong .dll? 
I've installed everything according to my  python version (3.12)

**Comment by Djanghost** [comment]
> You can also try adding "FULL_PATH\comfy_folder\python_embeded" and "FULL_PATH\comfy_folder\python_embeded\Scripts" to the Windows `PATH` (temporarily for testing) and don't forget to move it all up the list like this example:
> 
> ```
> C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64
> D:\ComfyUI_windows_portable_nvidia\python_embeded
> D:\ComfyUI_windows_portable_nvidia\python_embeded\Scripts
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\lib\x64
> everything else 1
> everything else 2
> ...
> ```

Same error doing this too :/

**Comment by Ratinod** [comment]
> Sorry but what does that mean ? That I have the wrong .dll?
> I've installed everything according to my python version (3.12)

I just want to know that [https://aka.ms/vs/17/release/vc\_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe) was installed successfully. And they match mine.

vcruntime140.dll ->right click -> "Properties"  -> file size
vcruntime140.dll ->right click -> "Properties" -> "Details" -> file version

**Comment by Djanghost** [comment]
vcruntime140.dll : (119 888b) 117k , 14.40.33816.0 
msvcp140.dll : (575 056b) 561k, 14.40.33816.0

Look same

**Comment by Djanghost** [comment]
It's quite frustrating because I upgraded to the new version of ComfyUI yesterday, on my previous Comfy version running Python 3.11, it managed to compile and work

**Comment by Ratinod** [comment]
I understand, because I recently reinstalled everything several times to solve the "colored cubes" problem. And the problem with DLL also occurred several times, but was eventually fixed.
And honestly, I don’t know what your problem might be.
Finally, you can try to delete "include" and "libs" folders from python_embeded and and install them from here again:
https://github.com/woct0rdho/triton-windows/releases/download/v3.0.0-windows.post1/python_3.12.7_include_libs.zip

If it doesn't help, then the only thing left is "dlltracer". But I haven't used it.

**Comment by Djanghost** [comment]
I've tried dlltracer too, but I can't install it in the portable version of comfyui.

I think I'll reinstall everything one last time, if it still doesn't work I'll go back to my backup version of Comfy with Python 3.11... but what a waste of time! 

Thanks a lot for your help

**Comment by Ratinod** [comment]
> I've tried dlltracer too, but I can't install it in the portable version of comfyui.

run cmd
`python_embeded\python.exe -m pip install dlltracer` 
from folder containded "run_nvidia_gpu.bat" not working?

**Comment by Djanghost** [comment]
Nope !

**Comment by Ratinod** [comment]
> Nope !

yeah... i tried... "ERROR: Failed building wheel for dlltracer"
but you can get .whl
https://files.pythonhosted.org/packages/10/b2/f9fbd83c919c67b3c1427958f1f3bbad454d535428fbad10b7ca4d787e81/dlltracer-1.0.3a1-cp312-cp312-win_amd64.whl
`python_embeded\python.exe -m pip install dlltracer-1.0.3a1-cp312-cp312-win_amd64.whl`

**Comment by Djanghost** [comment]
OK now it works !! I just reinstall the whole stuff (comfyUI, visual studio, cuda toolkit, PATH etc...). Thanks !

**Comment by Djanghost** [comment]
Closed
