### ISSUE TITLE
module 'folder_paths' has no attribute 'get_full_path_or_raise'

### ISSUE THREAD

**Issue by Pancat009** [kijai/ComfyUI-MochiWrapper#68]
Mochi VAE Encoder Loader reports error
module 'folder_paths' has no attribute 'get_full_path_or_raise'

I have downloaed the encoder vae and put it into /models/vae/mochi

**Comment by kijai** [comment]
`get_full_path_or_raise` is relatively new function added to base Comfy month or so ago, so this would mean your ComfyUI is not up to date.

**Comment by Pancat009** [comment]
comfyui version >= v0.2.3 will solve the issue :D
