### ISSUE TITLE
Does it support img2vid?

### ISSUE THREAD

**Issue by lijackcoder** [kijai/ComfyUI-MochiWrapper#7]
that's all

**Comment by strangePause** [comment]
Here it states they are working on image to video https://www.genmo.ai/blog#:~:text=Looking%20beyond%20this%20release%2C%20we%20are%20working%20on%20image%2Dto%2Dvideo%20capabilities

As of right now, I don't believe it is possible, no

**Comment by kijai** [comment]
The model does not support img2vid.
