### ISSUE TITLE
This action is not allowed with this security level configuration.

### ISSUE THREAD

**Issue by noizfactory** [kijai/ComfyUI-MochiWrapper#74]
Facing this error when trying to install the repo via the git url in the ComfyUI Manager since this does not show up in the Custom Nodes Manager list. I have cloned it manually for now but thought I should report it.

MacOS 15.0.1
ComfyUI: 2754[1b8089](2024-10-10)
Manager: V2.51.7

**Comment by kijai** [comment]
That's the default message when using the "install from git" option in general, nothing to do with this repo specifically. I haven't added this to Manager to avoid confusion as comfy has been working on the native implementation.

**Comment by noizfactory** [comment]
Understood, thanks @kijai. I'll close this issue in this case. If you don't mind another question/issue - is this currently not supported on Apple Silicon? I do see that the workflow is passing MPS mode to torch but it errors out when trying to use the example workflow.
