### ISSUE TITLE
Triton on Win11 is not detected

### ISSUE THREAD

**Issue by aluap99** [kijai/ComfyUI-MochiWrapper#78]
I successfully installed Triton using this guide: https://purz.notion.site/Get-Windows-Triton-working-for-Mochi-6a0c055e21c84cfba7f1dd628e624e97 on ComfyUI_portable but MochiSampler returns this runtime error:
![image](https://github.com/user-attachments/assets/adec46c8-5eda-40b7-8c66-dfb63686059c)

I am confident that Triton is installed correctly because I tested if it works using this script:
https://github.com/woct0rdho/triton-windows/?tab=readme-ov-file#test-if-it-works

Here's my ComfyUI workflow:
[workflow video1.json](https://github.com/user-attachments/files/17676887/workflow.video1.json)

ComfyUI logs:
[CWindowssystem32cmd.exe.txt](https://github.com/user-attachments/files/17676944/CWindowssystem32cmd.exe.txt)

**Comment by kijai** [comment]
Your pytorch version is really old, it says you have pytorch version: 2.3.1+cu121
You should update to 2.5.1+cu124

**Comment by aluap99** [comment]
It helped, thank you!
