### ISSUE TITLE
Comfy's fp8_scaled model doesn't work with the Mochi Model Loader

### ISSUE THREAD

**Issue by Jonseed** [kijai/ComfyUI-MochiWrapper#80]
Comfy's fp8_scaled is much better quality than fp8. Can you make your Mochi Model Loader work with fp8_scaled? Currently it just outputs pink noise.

![ComfyUI-spatial-tiling_00010_-ezgif com-webp-to-png-converter](https://github.com/user-attachments/assets/553d7f62-67b0-491e-bbf9-d17c1cb76147)

**Comment by kijai** [comment]
Not really compatible, also the quality of the fp8 scaled is pretty terrible.

**Comment by Jonseed** [comment]
Not in my testing, fp8_scaled was better quality than fp8, by far.

**Comment by kijai** [comment]
Can you show some comparisons? I've not been able to get anything usable of it, which GPU do you have?

https://github.com/user-attachments/assets/5482cbb1-8342-4584-94a9-11fcd338cf2d

**Comment by Jonseed** [comment]
I'm on 3060 12GB. Currently running another job. Will post comparison soon.

**Comment by kijai** [comment]
It seems to always run on fast mode on 4090, so maybe that affects it, but the fast mode with the normal fp8 does not affect it like that at all.

**Comment by Jonseed** [comment]
Hmm, I think I might be wrong. But I can't do a direct comparison because I don't know what sampler/scheduler you are using in the Mochi Sampler, since I have to use the KSampler to test the fp8_scaled model (which uses euler/simple).

**Comment by kijai** [comment]
> Hmm, I think I might be wrong. But I can't do a direct comparison because I don't know what sampler/scheduler you are using in the Mochi Sampler, since I have to use the KSampler to test the fp8_scaled model (which uses euler/simple).

Using euler and linear_quadratic is equal to the original. The above test was done so, and if both models were in bf16 the results are pretty much equal as well.

**Comment by Jonseed** [comment]
I'm still not getting the same output with euler/linear_quadratic. But after further testing it does look like fp8 is better, so I am wrong. You are right. And your nodes are about twice as fast sampling too (is that because of `accelerate`?). Not sure what I was looking at before when I thought fp8_scaled was better...
