### ISSUE TITLE
MochiSampler generates only 13 frames on RTX 4070 12GB. How to increase frames amount?

### ISSUE THREAD

**Issue by aluap99** [kijai/ComfyUI-MochiWrapper#81]
Using Mochi Sampler node and this workflow I can generate only 13 frames:
[oom_workflow.json](https://github.com/user-attachments/files/17686498/oom_workflow.json)

When increasing frames to 19 or higher I get OOM error on RTX 4070 Super 12GB.

But using another Mochi workflow (with KSampler node) I can generate 61 frames or even more:
https://www.reddit.com/r/StableDiffusion/comments/1gklsl2/comment/lvm9472/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I tried to link `mochi_model` output from `(Down)load Mochi Model` to KSampler input `model` but they are not compatible. 
Is there a way to get higher number of frames with MochiSampler or change it somehow to KSampler?

I used Mochi Sampler because I want to utilize triton and sage optimizations.

ComfyUI logs:
[OOM_CWindowssystem32cmd.exe.txt](https://github.com/user-attachments/files/17686500/OOM_CWindowssystem32cmd.exe.txt)

**Comment by Jonseed** [comment]
Is it OOM on the sampler node or on the decode node?

**Comment by kijai** [comment]
The GGUF model does use more VRAM than the fp8, the weight setting has no effect when GGUF is used as the precisions are handled internally with it. It's not about the sampler.

Comfy sampling probably also allows for the low vram mode which these nodes do not.

**Comment by aluap99** [comment]
> Is it OOM on the sampler node or on the decode node?

On sampler node

**Comment by aluap99** [comment]
> The GGUF model does use more VRAM than the fp8, the weight setting has no effect when GGUF is used as the precisions are handled internally with it. It's not about the sampler.
> 
> Comfy sampling probably also allows for the low vram mode which these nodes do not.

After I have changed the model to `mochi_preview_dit_fp8_e4m3fn.safetensors` I was able to generate 37 frames. Thanks for the help!
